[package]
name = "serde-evaluate"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_bytes = "0.11.10"
thiserror = "2.0.12"

[dev-dependencies]
